name: Build

on:
  push:
  pull_request:

  # Run automatically every monday
  schedule:
    - cron: 1 12 * * 1

jobs:
  firmware:
    strategy:
      matrix:
        os: ['macos-latest', 'ubuntu-latest']

      # Don't cancel all builds when one fails
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Arm GNU Toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1

    - name: Build
      run: make

    # Publish bootloader binary for latest Cynthion hardware revision
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bootloader-binaries
        path: |
          bootloader.bin
          bootloader.elf
      if: matrix.os == 'ubuntu-latest'
